<?xml version="1.0" encoding="utf-8"?>
<assemblies>
  <assembly name="silentFailure.dll" configFile="" run-date="2017-05-25" run-time="15:57:31" time="0.494" total="2" passed="1" failed="1" skipped="0" environment="64-bit .NET (unknown version) [collection-per-class, parallel (4 threads)]" test-framework="xUnit.net 2.2.0.3545">
    <class name="silentFailure.Class1" time="0.051" total="2" passed="1" failed="1" skipped="0">
      <test name="silentFailure.Class1.ThisShouldFail" type="silentFailure.Class1" method="ThisShouldFail" result="Fail" time="0.0455647">
        <failure exception-type="Xunit.Sdk.TrueException">
          <message>Assert.True() Failure\r\nExpected: True\r\nActual:   False</message>
          <stack-trace>   at silentFailure.Class1.ThisShouldFail() in C:\Dropbox\OSS\ghuntley\cakerepro\silentFailure\Class1.cs:line 15</stack-trace>
        </failure>
      </test>
      <test name="silentFailure.Class1.ThisShouldPass" type="silentFailure.Class1" method="ThisShouldPass" result="Pass" time="0.0049922" />
    </class>
  </assembly>
</assemblies>